// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZNinVWj1iXM37855qiytLjkAPNDIuucw',
    appId: '1:253104695593:web:1ac7a5a9951922810a6f38',
    messagingSenderId: '253104695593',
    projectId: 'project-ad28f',
    authDomain: 'project-ad28f.firebaseapp.com',
    storageBucket: 'project-ad28f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnNUyg9lb5_sdmM8sVsdDGEkea8diINmE',
    appId: '1:253104695593:android:2deb51aa30ed96710a6f38',
    messagingSenderId: '253104695593',
    projectId: 'project-ad28f',
    storageBucket: 'project-ad28f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSiXW1eaXYCvEZdB0QwXq2FuBdf_4dWFc',
    appId: '1:253104695593:ios:18c3a50c68ddd1cc0a6f38',
    messagingSenderId: '253104695593',
    projectId: 'project-ad28f',
    storageBucket: 'project-ad28f.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSiXW1eaXYCvEZdB0QwXq2FuBdf_4dWFc',
    appId: '1:253104695593:ios:20f48c5dfc0339780a6f38',
    messagingSenderId: '253104695593',
    projectId: 'project-ad28f',
    storageBucket: 'project-ad28f.appspot.com',
    iosBundleId: 'com.example.weatherApp.RunnerTests',
  );
}
